import { html, Component } from './lib.js';
import { human, measurementText, historySeries, forecastModel, settingsPayload, quotaRows, adminMutation, attentionFreshness } from './operator.js';
const date=value=>value&&Number.isFinite(Date.parse(value))?new Date(value).toLocaleString():'Not reported';
const text=value=>value==null?'Unknown':String(value);
const Panel=({title,note,children})=>html`<section class="panel operator-panel"><div class="panel-head"><h3>${title}</h3>${note?html`<span class="note">${note}</span>`:null}</div><div class="panel-pad">${children}</div></section>`;
const Tag=({state})=>html`<span class=${`operator-tag operator-${state || 'unknown'}`}>${human(state)}</span>`;
const Evidence=({value,title='Supporting observations'})=>html`<details class="operator-evidence"><summary>${title}</summary><pre>${JSON.stringify(value ?? {state:'unknown'},null,2)}</pre></details>`;
const ObjectLink=({nodeId,objectId})=>html`<div class="operator-links">${nodeId?html`<a href=${`#node/${encodeURIComponent(nodeId)}${objectId?`/object/${encodeURIComponent(objectId)}`:''}`}>Host storage context</a>`:null}${objectId?html`<a href=${`#ops/history/${encodeURIComponent(objectId)}`}>Metric history & capacity runway</a>`:null}</div>`;

export class AdminAction extends Component {
  constructor(p){super(p);this.state={busy:false,error:'',success:''};this.abort=new AbortController();}
  componentWillUnmount(){this.closed=true;this.abort.abort();}
  async submit(event){event.preventDefault();const form=event.currentTarget;const input=form.elements.namedItem('administrator');let credential=input.value;input.value='';this.setState({error:'',success:''});
    try{const payload=this.props.payload(form);this.setState({busy:true});await adminMutation(this.props.path,this.props.method,credential,payload,{signal:this.abort.signal});credential='';if(!this.closed){this.setState({busy:false,success:this.props.success || 'Action saved.'});this.props.onSuccess?.();}}
    catch(error){credential='';if(!this.closed)this.setState({busy:false,error:error.message});}
  }
  render(p,s){return html`<form class="operator-admin" onSubmit=${e=>this.submit(e)} autocomplete="off"><fieldset disabled=${s.busy}><legend>${p.title}</legend>${p.children}<label>Administrator credential for this action<input name="administrator" type="password" required autocomplete="new-password" spellcheck="false" placeholder="Paste administrator credential"/></label><p class="note">This action requires administrator access. The credential is cleared on submission and is never saved in browser storage.</p><button class="btn btn-primary" type="submit">${s.busy?'Saving…':p.button || 'Save action'}</button></fieldset>${s.error?html`<p class="connection-error" role="alert">${s.error}</p>`:null}${s.success?html`<p class="operator-success" role="status">${s.success}</p>`:null}</form>`;}
}
const Attention=({rows,summary,summaryError,summaryAt,summaryState,refresh})=>html`<div class="stack">
  <${Panel} title="Attention queue" note="Evidence for an administrator to assess"><div class="operator-kpis">${[['Open concerns',summary?.open],['Unacknowledged',summary?.unacknowledged],['Recorded episodes',summary?.total]].map(([label,value])=>html`<div><span>${label}</span><strong>${text(value)}</strong></div>`)}</div><p class="note">Live summary read: ${date(summaryAt)} · Evaluation: <${Tag} state=${summaryState || 'unknown'}/> · Last successful evaluation: ${date(summary?.reconciliation?.last_successful_at)}</p>${summaryError?html`<p class="connection-error" role="status">${summaryError} Previous summary is dated context.</p>`:null}<p class="note">Acknowledgement records your review. It does not resolve the condition. New severity or a new episode requires a separate review.</p><${Evidence} value=${summary?.delivery} title="Notification delivery counts"/><//>
  ${rows.length?rows.map(row=>html`<article class=${`operator-concern operator-concern-${row.severity || 'unknown'}`} key=${row.id}><header><div><span class="eyebrow-accent">${human(row.kind)}</span><h3>${row.summary || 'Concern summary unavailable'}</h3></div><div class="operator-tags"><${Tag} state=${row.severity}/><${Tag} state=${row.status}/></div></header><dl class="operator-facts"><div><dt>Observation</dt><dd><${Tag} state=${row.observation_state}/> · Evaluation ${human(row.reconciliation_state || 'unknown')}</dd></div><div><dt>First observed</dt><dd>${date(row.first_seen_at)}</dd></div><div><dt>Updated</dt><dd>${date(row.updated_at)}</dd></div><div><dt>Host / object</dt><dd><code>${row.node_id || 'Unknown'} / ${row.object_id || 'Host level'}</code></dd></div><div><dt>Notification</dt><dd>${human(row.notification?.state || 'not_reported')}${row.notification?.reason?` · ${human(row.notification.reason)}`:''}</dd></div><div><dt>Acknowledgement</dt><dd>${row.acknowledgement?`Reviewed ${date(row.acknowledgement.at)}`:'Not acknowledged'}</dd></div></dl>${row.acknowledgement?.note?html`<p class="operator-note">${row.acknowledgement.note}</p>`:null}<${ObjectLink} nodeId=${row.node_id} objectId=${row.object_id}/><${Evidence} value=${row.evidence}/>${row.status==='open'&&!row.acknowledgement?html`<details class="operator-action-detail"><summary>Acknowledge this episode</summary><${AdminAction} key=${row.revision} title="Record your review" button="Acknowledge episode" path=${`/api/v1/attention/${encodeURIComponent(row.id)}/acknowledgement`} method="POST" payload=${form=>({expected_revision:row.revision,note:form.elements.namedItem('note').value})} success="Acknowledgement saved. The source condition remains independent." onSuccess=${refresh}><label>Review note<textarea name="note" maxlength="2048" rows="3" placeholder="Optional context for your review"/></label><//></details>`:null}</article>`):html`<p class="empty-note">No episodes in this snapshot. Check evaluation freshness above; missing evidence does not establish healthy storage.</p>`}
</div>`;
class Settings extends Component {
 constructor(p){super(p);this.state={enabled:p.settings.enabled===true};}
 render({settings,refresh},s){return html`<${Panel} title="Administrator notifications" note="Twilio SMS"><div class="operator-kpis"><div><span>Sending</span><strong>${settings.enabled===true?'Enabled':settings.enabled===false?'Disabled':'Unknown'}</strong></div><div><span>Server credentials</span><strong>${human(settings.credential_state)}</strong></div><div><span>Worker last seen</span><strong class="operator-date">${date(settings.worker_seen_at)}</strong></div></div><dl class="operator-facts"><div><dt>Current sender</dt><dd>${settings.sender || 'Not configured'}</dd></div><div><dt>Current recipient</dt><dd>${settings.recipient || 'Not configured'}</dd></div><div><dt>Updated</dt><dd>${date(settings.updated_at)}</dd></div></dl>${settings.admission_limited?html`<p class="connection-error">The notification queue is at its admission limit. Some concerns may not have been queued.</p>`:null}<p class="note">Saving an enabled configuration permits future new or escalating concerns to send SMS. Previously suppressed notifications are not resent. Provider acceptance is separate from handset delivery.</p><${AdminAction} title="Change notification settings" button="Save notification settings" path="/api/v1/notifications/settings" method="PUT" payload=${form=>settingsPayload(settings,{enabled:s.enabled,sender:form.elements.namedItem('sender').value,recipient:form.elements.namedItem('recipient').value})} onSuccess=${refresh}><div class="operator-form-grid"><label>New sender number<input name="sender" type="tel" autocomplete="off" placeholder="Leave blank to keep current"/></label><label>New recipient number<input name="recipient" type="tel" autocomplete="off" placeholder="Leave blank to keep current"/></label></div><p class="note">Use international phone format, for example +15555550123. Blank fields preserve the current masked number.</p><label class="operator-checkbox"><input type="checkbox" checked=${s.enabled} onChange=${e=>this.setState({enabled:e.target.checked})}/>Enable SMS for future new or escalating concerns</label><//><//>`;}
}
const Quotas=({rows,meta})=>html`<${Panel} title="Configured NFS user quotas" note="Server filesystem / UID scope"><p class="note">Coverage: ${human(meta?.coverage?.state)} · ${text(meta?.coverage?.available_targets)} available of ${text(meta?.coverage?.configured_targets)} configured targets. Export paths can share one filesystem quota; these rows must not be summed. APFS volume quotas are separate.</p>${rows.length?html`<div class="table-scroll"><table class="live-table operator-table"><thead><tr><th>Server / export / user</th><th>Observation</th><th>Used bytes</th><th>Block soft / hard limit</th><th>Inodes used / limits</th><th>Grace / enforcement</th></tr></thead><tbody>${quotaRows(rows).map(q=>html`<tr key=${q.quota_id}><td><strong>${q.display_label || q.server || 'Unknown server'}</strong><div>${q.server || 'Unknown server'}:${q.export_path || 'Unknown export'}</div><div class="note">UID ${text(q.uid)} · ${q.node_name || q.node_id}</div><${ObjectLink} nodeId=${q.node_id}/></td><td><${Tag} state=${q.state}/><div class="note">${human(q.reason)}<br/>${date(q.observed_at)}</div></td><td class="operator-exact">${q.used}</td><td class="operator-exact">Soft: ${q.soft}<br/>Hard: ${q.hard}</td><td class="operator-exact">Used: ${q.inodeUsed}<br/>Soft: ${q.inodeSoft}<br/>Hard: ${q.inodeHard}</td><td>Blocks: ${human(q.grace?.block?.state)}<br/>Inodes: ${human(q.grace?.inode?.state)}<div class="note">Block deadline: ${date(q.grace?.block?.deadline)}<br/>Enforcement: ${q.active===true?'active':q.active===false?'inactive':'unknown'}</div><${Evidence} value=${q} title="Quota evidence"/></td></tr>`)}</tbody></table></div>`:html`<p class="empty-note">No configured quota rows in this snapshot. Configuration and collection coverage remain ${human(meta?.coverage?.state)}.</p>`}<//>`;
const Diagnostics=({rows})=>html`<${Panel} title="Storage diagnostics" note="Passive source readiness and accessibility"><p class="note">These observations describe collector readiness and filesystem accessibility. Filesystem integrity remains unknown; no repair or active self-test is performed.</p>${rows.length?html`<div class="operator-diagnostics">${rows.map(r=>html`<article class="operator-diagnostic" key=${r.object_id}><header><h4>${r.label || 'Storage object'}</h4><span class="note">${r.node_name || r.node_id} · ${human(r.kind)}</span></header>${(r.diagnostics?.checks || []).map(c=>html`<div class="operator-check"><strong>${c.collector}</strong><${Tag} state=${c.state}/><span>${human(c.reason)}</span><span class="note">${date(c.observed_at)}</span></div>`)}${r.diagnostics?.accessibility?html`<div class="operator-check"><strong>Filesystem accessibility</strong><${Tag} state=${r.diagnostics.accessibility.state}/><span>${human(r.diagnostics.accessibility.reason)}</span><span class="note">Observation: ${human(r.diagnostics.accessibility.observation_state)} · ${date(r.diagnostics.accessibility.observed_at)}</span></div>`:null}${r.diagnostics?.capacity_collection?html`<div class="operator-check"><strong>Capacity collection</strong><${Tag} state=${r.diagnostics.capacity_collection.state}/><span>${human(r.diagnostics.capacity_collection.reason)}</span><span class="note">${date(r.diagnostics.capacity_collection.observed_at)}</span></div>`:null}<${ObjectLink} nodeId=${r.node_id} objectId=${r.object_id}/><${Evidence} value=${r.diagnostics}/></article>`)}</div>`:html`<p class="empty-note">No diagnostic objects in this snapshot. Missing source observations remain unknown.</p>`}<//>`;
const Forecast=({data,error})=>{const f=forecastModel(data);return html`<${Panel} title="Capacity runway" note="Capacity exhaustion scenario"><div class="operator-forecast"><div><span class="eyebrow-accent">${f.date?'Estimated exhaustion':'Estimate unavailable'}</span><div class="operator-forecast-date">${f.date?date(f.date):'Unknown'}</div><${Tag} state=${f.state}/></div><div>${f.range?html`<p>Scenario range<br/><strong>${date(f.range.earliest_at)} — ${date(f.range.latest_at)}</strong></p>`:html`<p>${f.reasons.map(human).join(' · ')}</p>`}<p class="note">Capacity exhaustion only. This is not a drive failure prediction or a guaranteed replacement date. The forecast always uses the latest 24 hours of paired capacity observations, independently of the selected history window.</p></div></div>${error?html`<p class="connection-error">${error}</p>`:null}<dl class="operator-facts"><div><dt>Evidence span</dt><dd>${text(f.basis.sample_count)} paired observations<br/>${date(f.basis.observed_from)} — ${date(f.basis.observed_to)}</dd></div><div><dt>Capacity / used</dt><dd class="operator-exact">${text(f.basis.capacity_bytes)} / ${text(f.basis.used_bytes)} bytes</dd></div><div><dt>Estimated growth</dt><dd>${text(f.basis.growth_bytes_per_second)} bytes/second</dd></div></dl>${f.assumptions.length?html`<ul class="operator-assumptions">${f.assumptions.map(a=>html`<li>${a}</li>`)}</ul>`:null}<${Evidence} value=${f.basis} title="Forecast basis"/><//>`;};
const History=({data,forecast,forecastError})=>html`<div class="stack"><${Forecast} data=${forecast} error=${forecastError}/>${historySeries(data).map(s=>html`<${Panel} key=${s.key} title=${`${s.identity.metric || data.metric} · ${s.identity.source || 'Unknown source'}`} note=${`${s.rows.length} stored observations`}><dl class="operator-facts"><div><dt>Boot / generation</dt><dd><code>${text(s.identity.boot_id)} / ${text(s.identity.inventory_generation)}</code></dd></div><div><dt>Scope / units</dt><dd>${text(s.identity.scope)} / ${s.unit}</dd></div><div><dt>Labels</dt><dd><code>${JSON.stringify(s.identity.labels || {})}</code></dd></div></dl>${s.dots.length?html`<div class="operator-history-chart"><div class="operator-chart-labels"><span>${s.maxLabel} ${s.unit}</span><span>${s.minLabel} ${s.unit}</span></div><svg viewBox="0 0 600 155" role="img" aria-label=${`${s.identity.metric} observations, ${s.start} to ${s.end}, ${s.minLabel} to ${s.maxLabel} ${s.unit}`} preserveAspectRatio="none">${s.dots.map(p=>html`<circle cx=${p.x} cy=${p.y} r="3" fill="currentColor"><title>${p.at}: ${p.value} ${s.unit}</title></circle>`)}</svg><div class="chart-x-axis note"><span>${date(s.start)}</span><span>${date(s.end)}</span></div></div>`:html`<p class="empty-note">No fully usable numeric observations to plot in this series.</p>`}<p class="note">Dated points show available observations without implying continuity between samples. Unknown and partial observations remain in the evidence table. Plot positions are approximate; exact source values are below.</p><details class="operator-evidence" open=${s.rows.length<=20}><summary>Exact observation table · ${s.rows.length} rows</summary><div class="table-scroll"><table class="live-table operator-table"><thead><tr><th>Source date</th><th>${data.resolution==='raw'?'Exact value':'Mean (approximate)'}</th><th>State / gap</th><th>Coverage / derivation</th></tr></thead><tbody>${s.rows.map((p,i)=>html`<tr key=${i}><td>${date(p.at)}<div class="note">${p.at}</div></td><td class="operator-exact">${text(p.value)} ${s.unit}${data.resolution!=='raw'?html`<div class="note">Min ${text(p.min)} / max ${text(p.max)}</div>`:null}</td><td><${Tag} state=${p.state}/>${p.gap_before?html`<div class="note">Gap before this observation</div>`:null}</td><td>${p.coverage}<div class="note">${p.derivation_state?human(p.derivation_state):''}${p.elapsed_since_previous_seconds!=null?` · ${p.elapsed_since_previous_seconds}s since previous`:''}</div>${p.state_counts?html`<code>${JSON.stringify(p.state_counts)}</code>`:null}</td></tr>`)}</tbody></table></div></details><//>`)}${!data?.series?.length?html`<p class="empty-note">No stored observations match this selection. Missing history has not been backfilled.</p>`:null}</div>`;

const tabs=[['attention','Attention'],['notifications','Notifications'],['quotas','NFS quotas'],['diagnostics','Diagnostics'],['history','Metric history']];
const initialTab=p=>p.objectId||p.route==='history'||p.route?.tab==='history'||p.route?.section==='history'?'history':tabs.some(([id])=>id===p.route)?p.route:tabs.some(([id])=>id===p.route?.section)?p.route.section:'attention';
/** Root integration: <OperationsView client={ApiClient} route={'attention'|'history'} objectId={id}/>. */
export class OperationsView extends Component {
 constructor(p){super(p);const now=Date.now();this.state={tab:initialTab(p),data:null,meta:null,error:'',busy:false,summary:null,summaryError:'',summaryAt:null,forecast:null,forecastError:'',cursors:[null],page:0,object:p.objectId || '',metric:'used_bytes',from:new Date(now-6*3600000).toISOString(),to:new Date(now-5000).toISOString(),resolution:'raw'};this.epoch=0;this.pages=[];}
 componentDidMount(){this.load();this.summaryTimer=setInterval(()=>{if(this.state.tab==='attention'&&!this.props.attentionSummary&&!document.hidden)this.summary();},3000);}
 componentDidUpdate(prev){if(prev.client!==this.props.client||prev.objectId!==this.props.objectId||(prev.route?.section || prev.route)!==(this.props.route?.section || this.props.route)){this.epoch++;this.pages=[];this.setState({tab:initialTab(this.props),object:this.props.objectId || '',data:null,meta:null,error:'',summary:null,cursors:[null],page:0},()=>this.load());}}
 componentWillUnmount(){this.closed=true;this.epoch++;clearInterval(this.summaryTimer);}
 async summary(){if(this.props.attentionSummary||this.summaryBusy||!this.props.client)return;this.summaryBusy=true;const client=this.props.client;try{const r=await client.get('/api/v1/attention/summary');if(!this.closed&&client===this.props.client)this.setState({summary:r.data,summaryAt:r.meta.server_time,summaryWall:Date.now(),summaryMono:performance.now(),summaryError:''});}catch(e){if(!this.closed&&client===this.props.client)this.setState({summaryError:e.message});}finally{this.summaryBusy=false;}}
 choose(tab){location.hash=`#ops/${tab}${tab==='history'&&this.state.object?`/${encodeURIComponent(this.state.object)}`:''}`;}
 refresh(){return this.load(null,0,[null],true);}
 async load(cursor=null,targetPage=this.state.page,targetCursors=this.state.cursors,fresh=false){const client=this.props.client;if(!client)return;const ticket=++this.epoch;const {tab,object,metric,from,to,resolution}=this.state;
   if(tab==='history'&&!object.trim()){this.setState({data:null,meta:null,busy:false});return;}
   this.setState({busy:true,error:''});if(tab==='attention')this.summary();
   try {let response,extra={};const cached=!fresh&&this.pages[targetPage]?.cursor===cursor?this.pages[targetPage].response:null;if(cached){response=cached;}else if(tab==='history'){
      if(!Number.isFinite(Date.parse(from))||!Number.isFinite(Date.parse(to)))throw new Error('Enter valid RFC3339 dates with a timezone.');
      const base=`/api/v1/objects/${encodeURIComponent(object.trim())}`;const [history,forecast]=await Promise.allSettled([client.get(`${base}/history`,{metric,from,to,resolution}),client.get(`${base}/capacity-forecast`)]);if(history.status==='rejected')throw history.reason;response=history.value;extra={forecast:forecast.status==='fulfilled'?forecast.value.data:null,forecastError:forecast.status==='rejected'?forecast.reason.message:''};
    }else response=await client.get(tab==='notifications'?'/api/v1/notifications/settings':`/api/v1/${tab}`,tab==='notifications'?{}:{limit:100,cursor,...(tab==='attention'?{status:'all'}:{})});
    if(ticket!==this.epoch||this.closed)return;if(tab!=='history'&&tab!=='notifications'&&!Array.isArray(response.data))throw new Error('The server returned an invalid collection.');if(['attention','quotas','diagnostics'].includes(tab)){if(fresh)this.pages=[];this.pages[targetPage]={cursor,response};}this.setState({data:response.data,meta:response.meta,busy:false,page:targetPage,cursors:targetCursors,...extra});
   }catch(e){if(ticket===this.epoch&&!this.closed)this.setState({busy:false,error:e.message});}
 }
 next(){const cursor=this.state.meta?.next_cursor;if(!cursor)return;const page=this.state.page+1;const cursors=[...this.state.cursors.slice(0,page),cursor];return this.load(cursor,page,cursors);}
 previous(){const page=this.state.page-1;if(page<0)return;return this.load(this.state.cursors[page],page);}
 render(p,s){const paged=['attention','quotas','diagnostics'].includes(s.tab);return html`<div class="stack operator-view"><nav class="operator-tabs" aria-label="Operator workflows">${tabs.map(([id,label])=>html`<button class=${`btn ${id===s.tab?'operator-tab-active':''}`} aria-current=${id===s.tab?'page':undefined} onClick=${()=>this.choose(id)}>${label}</button>`)}</nav>
 ${s.tab==='history'?html`<${Panel} title="Stored metric history" note="Bounded source evidence"><form class="operator-history-form" onSubmit=${e=>{e.preventDefault();const target=`#ops/history/${encodeURIComponent(s.object.trim())}`;if(location.hash!==target)location.hash=target;else this.refresh();}}><div class="operator-form-grid"><label>Storage object ID<input value=${s.object} onInput=${e=>this.setState({object:e.target.value})} required placeholder="Object UUID"/></label><label>Metric name<input value=${s.metric} onInput=${e=>this.setState({metric:e.target.value})} required maxlength="128" placeholder="used_bytes" list="operator-metrics"/><datalist id="operator-metrics">${['used_bytes','capacity_bytes','device_read_bytes_total','device_write_bytes_total'].map(v=>html`<option value=${v}/>` )}</datalist></label><label>From (RFC3339)<input value=${s.from} onInput=${e=>this.setState({from:e.target.value})} required/></label><label>To (RFC3339)<input value=${s.to} onInput=${e=>this.setState({to:e.target.value})} required/></label><label>Resolution<select value=${s.resolution} onChange=${e=>this.setState({resolution:e.target.value})}><option value="raw">Raw · past 24 hours</option><option value="5m">5 minutes · past 30 days</option><option value="1h">1 hour · past 365 days</option></select></label></div><button class="btn btn-primary" disabled=${s.busy} type="submit">${s.busy?'Loading…':'Load history & runway'}</button><p class="note">Up to 2,000 points across all series. Narrow the dates or choose rollups if the selection is too large. No missing history is backfilled.</p></form><//>`:null}
 <div class="operator-page-state"><div class="page-buttons">${s.tab!=='history'?html`<button class="btn" disabled=${s.busy} onClick=${()=>this.refresh()}>${s.busy?'Loading…':'Refresh snapshot'}</button>`:null}${paged?html`<button class="btn" disabled=${s.busy||s.page===0} onClick=${()=>this.previous()}>Previous</button><button class="btn" disabled=${s.busy||!s.meta?.next_cursor} onClick=${()=>this.next()}>Next</button>`:null}</div><p class="note" role="status">${s.meta?`Snapshot ${date(s.meta.server_time)}${paged?` · page ${s.page+1} · ${s.data?.length || 0} rows`:''}. Evidence remains frozen until refreshed.`:s.busy?'Loading source observations…':'No snapshot loaded.'}${s.tab==='attention'?' Live summary refreshes independently of the frozen evidence table.':''}</p>${s.error?html`<p class="connection-error" role="alert">${s.error}${s.data?' Previous snapshot remains for dated reference.':''}</p>`:null}</div>
 ${s.data?s.tab==='attention'?html`<${Attention} rows=${s.data} summary=${p.attentionSummary?.data || s.summary} summaryError=${p.attentionSummary?.error || s.summaryError} summaryAt=${p.attentionSummary?.server_time || s.summaryAt} summaryState=${attentionFreshness(p.attentionSummary || {data:s.summary,server_time:s.summaryAt,receivedWall:s.summaryWall,receivedMono:s.summaryMono,error:s.summaryError})} refresh=${()=>this.refresh()}/>`:s.tab==='notifications'?html`<${Settings} key=${s.data.revision} settings=${s.data} refresh=${()=>this.refresh()}/>`:s.tab==='quotas'?html`<${Quotas} rows=${s.data} meta=${s.meta}/>`:s.tab==='diagnostics'?html`<${Diagnostics} rows=${s.data}/>`:html`<${History} data=${s.data} forecast=${s.forecast} forecastError=${s.forecastError}/>`:!s.busy&&!s.error?html`<p class="empty-note">${s.tab==='history'?'Select a storage object to inspect its recorded history.':'No source snapshot is available.'}</p>`:null}
 </div>`;}
}

/** Mount once globally; optional onSummary(snapshot) shares reads with OperationsView. */
export class AttentionIndicator extends Component {
 constructor(p){super(p);this.state={data:null,server_time:null,error:''};}
 componentDidMount(){this.poll();}
 componentDidUpdate(prev){if(prev.client!==this.props.client){clearTimeout(this.timer);this.setState({data:null,server_time:null,error:''},()=>this.poll());}}
 componentWillUnmount(){this.closed=true;clearTimeout(this.timer);}
 async poll(){const client=this.props.client;if(!client||this.closed)return;let delay=3000;try{const r=await client.get('/api/v1/attention/summary');if(!this.closed&&client===this.props.client){const value={data:r.data,server_time:r.meta.server_time,error:'',receivedWall:Date.now(),receivedMono:performance.now()};this.setState(value);this.props.onSummary?.(value);}}
 catch(error){delay=Math.max(delay,(error.retryAfter||0)*1000);if(!this.closed&&client===this.props.client){const value={...this.state,error:error.message};this.setState({error:error.message});this.props.onSummary?.(value);if([401,403].includes(error.status))this.props.onAuth?.(error);}}
 finally{if(!this.closed&&client===this.props.client){clearTimeout(this.timer);this.timer=setTimeout(()=>this.poll(),Math.max(document.hidden?30000:3000,delay));}}}
 render(p,s){const state=attentionFreshness(s);return html`<aside class=${`operator-attention-indicator ${s.data?.unacknowledged>0?'attention-present':''}`} aria-label="Attention summary"><a href="#ops/attention">${text(s.data?.unacknowledged)} unacknowledged · ${text(s.data?.open)} open concerns</a><span class="note">Evaluation: <${Tag} state=${state}/> · ${date(s.data?.reconciliation?.last_successful_at)}</span>${s.error?html`<span class="note" role="status">Summary unavailable; prior counts are dated.</span>`:null}</aside>`;}
}
